### ISSUE TITLE
Fail to submit transaction

### ISSUE THREAD

**Issue by dehezhang2** [ibm-cloud-docs/blockchain#244]
In the last step: `node invoke-transactions.js` doesn't work, here is the error message:
`2019-08-15T01:36:53.681Z - error: [Network]: _initializeInternalChannel: no suitable peers available to initialize from
Failed to submit transaction: Error: no suitable peers available to initialize from`
I think the error happens when the line 40: `const network = await gateway.getNetwork(channelName);` is executed.
The [solution on StackOverflow](https://stackoverflow.com/questions/56455251/error-no-suitable-peers-available-to-initiize-from-when-querying-the-blockcha) doesn't work.

**Comment by pamandrejko** [comment]
@nikhil550 Could you take a look at this issue?

**Comment by nikhil550** [comment]
Thanks @dehezhang2 for reaching out. This error looks likely to be an service discovery error. Did you configure anchor peers on your channel? 

The documentation does mention the need to configure anchor peers, but given how many errors come from that step, it could be made more prominent.

**Comment by pamandrejko** [comment]
@negupta - Can you paste a link in here to the docs where you tried to make this more clear

**Comment by tomxucnxa** [comment]
I am facing the same issue.
Anchor peers are configured, discovery is enabled in connection profile...
Query chaincode is fine, but submitting transaction gets failed.

**Comment by tomxucnxa** [comment]
But eventually it gets success, after double check and confirmation.
Anchor peers are added. Attached all files:
[application.tar.gz](https://github.com/ibm-cloud-docs/blockchain/files/3548916/application.tar.gz)

**Comment by nikhil550** [comment]
Hi @tomxucnxa, what updates did you make to the connection profile? Did you need to download a new connection profile after you updated your anchor peers?

**Comment by tomxucnxa** [comment]
@nikhil550 It seems that the connection profile has not any change.
I suggest making a 'query' (evaluateTransaction) calling to confirm the basic network health.
And, please ignore section '_channels' in my connection profile, that is for testing purpose.
