### ISSUE TITLE
IBM Blockchain Platform Extension for VS Code disconnects from WSL Ubuntu

### ISSUE THREAD

**Issue by keith-harrison-broninski** [ibm-cloud-docs/blockchain#250]
On opening the extension, VS Code disconnects from WSL Ubuntu and cannot reconnect.

Also, the Extension icon is not shown in the navigation bar, just a blank spot where it should be (still clickable to open the extension).

Windows 10 Pro 10.0.18362
Visual Studio Code 1.37.1
IBM Blockchain Platform Extension for VS Code 1.0.8

**Comment by pamandrejko** [comment]
Thank you Keith. We are looking into this and will get back to you.

**Comment by cazfletch** [comment]
Hi @keith-harrison-broninski the icon disappearing is a problem with VS Code that we have no control over.

Can you provide some more details for the other problem please? You say when you open the extension VS Code disconnects from WSL Ubuntu i'm not sure what you mean by this

**Comment by keith-harrison-broninski** [comment]
Hi @cazfletch 
On opening the extension, for example by clicking where the icon should be, it shows the panels for the extension but at the bottom left hand side instead of "WSL: Ubuntu" it changes to "Disconnected from WSL: Ubuntu", and brings up a dialog "Attempting to reconnect...".
Best, Keith

![VS Code before opening IBM Blockchain Extension](https://user-images.githubusercontent.com/2794023/64021264-721c4b80-cb2b-11e9-8797-4238c09b3556.PNG)
![VS Code after opening IBM Blockchain Extension](https://user-images.githubusercontent.com/2794023/64021262-721c4b80-cb2b-11e9-95e7-a6a3acd29a51.PNG)

**Comment by cazfletch** [comment]
Oh you are using the new remote feature in vscode - can you raise this issue here https://github.com/IBM-Blockchain/blockchain-vscode-extension/ please and i will look into it

**Comment by keith-harrison-broninski** [comment]
@cazfletch 

https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1357

Closing this one

Thanks, Keith
