### ISSUE TITLE
MSP does not need to join a consortium to join an existing channel

### ISSUE THREAD

**Issue by aldredb** [ibm-cloud-docs/blockchain#251]
The statement below in the documentation https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-console-join-network#ibp-console-join-network-add-org2 is not correct:

```
As we noted earlier, a peer organization must be known to the ordering service before it can create or join a channel (this is also known as joining the "consortium", the list of organizations known to the ordering service).
```
It is *okay* for an organization to not be in a consortium to join an existing channel, according to:
* https://hyperledger-fabric.readthedocs.io/en/release-1.4/network/network.html#the-sample-network
* My attempt to add `org2msp` that is not included in a consortium to an existing channel (view screenshots below). In the consortium, there is `org1msp` only but in `channel1`, there are both `org1msp` and `org2msp`
* Viewing the system channel block configuration

![3](https://user-images.githubusercontent.com/45155724/65574379-e964c400-df9f-11e9-80c9-e1c7ca55110b.png)
![2](https://user-images.githubusercontent.com/45155724/65574380-e9fd5a80-df9f-11e9-82bd-43e7664bf262.png)
![1](https://user-images.githubusercontent.com/45155724/65574383-e9fd5a80-df9f-11e9-911e-761c7cd9c115.png)

**Comment by pamandrejko** [comment]
Thank you for your feedback. We will take a look.

**Comment by joealewine** [comment]
Thank you for bringing this to our attention. This has now been fixed in prod. 

https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-console-build-network#ibp-console-build-network-add-org
