### ISSUE TITLE
last updated date is not showing up correctly 

### ISSUE THREAD

**Issue by horeaporutiu** [ibm-cloud-docs/blockchain#252]
![Screen Shot 2019-10-25 at 11 11 33 AM](https://user-images.githubusercontent.com/10428517/67594063-65296c00-f718-11e9-8940-ceefbc8b4d9e.png)

https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-ibp-console-build-network#ibp-console-build-network

**Comment by pamandrejko** [comment]
Thanks for reporting this.

PR: https://github.ibm.com/cloud-docs/blockchain/pull/1970

Fix should show up in Prod in about 30 mins after the build completes.

**Comment by pamandrejko** [comment]
Fixed. Closing.
