### ISSUE TITLE
  Request for more info on key management

### ISSUE THREAD

**Issue by rmm-sk** [ibm-cloud-docs/blockchain#255]
"These keys are stored in the browser when they are added to the member's blockchain wallet so that the console can use them to manage blockchain components."
 - will the console itself require a private key issued off the IBP CA?
 - if yes, can the description of the key creation process be included in this doc (outlining where private key created & stored - indicating if HSM will be used when it is available in IBP V2).
 - Can editor update document with a diagram showing key management architecture around the "member's blockchain wallet"? HSM and non-HSM wallet types.  
 - when HSMs are available in IBP V2, will the private key still be made available in the console?

**Comment by pamandrejko** [comment]
Thank  you for your comments here. When HSM support is added to the product we can address these questions.

**Comment by pamandrejko** [comment]
closing - duplicate
