### ISSUE TITLE
Clarification request for info in Key Management section

### ISSUE THREAD

**Issue by rmm-sk** [ibm-cloud-docs/blockchain#256]
"Although you can use the IBM Blockchain Platform console to generate private keys, those keys are not permanently stored by the console or the cloud (**public keys, on the other hand, are stored in the browser and added to the member's wallet so that the console can use them to manage blockchain components**), making customers ultimately responsible for the storage, backup, and disaster recovery of their keys."
 - how will the console use a "public key" to manage blockchain components? I would think that functionality requires access to the "private" key.

**Comment by pamandrejko** [comment]
@rmm-sk Thank you for your feedback on this topic. I am updating it to say:

```Although you use the IBM Blockchain Platform console to generate the certificates and private keys, they are not _permanently_ stored by the browser or the cloud database. Public and private keys are temporarily stored in the browser and added to the member's wallet so that the console can use the private key to digitally sign transactions. Customers are ultimately responsible for exporting the keys and managing their storage, backup, and disaster recovery. ```

Does this answer your question?

**Comment by pamandrejko** [comment]
No response in 3 months after addressing issue so closing.
