### ISSUE TITLE
Prohibited term: whitelist

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/blockchain#261]
Do not use. Use "allowlist" instead. Use as a noun. 

https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-import-nodes

**Comment by pamandrejko** [comment]
Fix and published here: https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-import-nodes#ibp-console-import-icp
