### ISSUE TITLE
Repetition in doc

### ISSUE THREAD

**Issue by alfalfs** [ibm-cloud-docs/blockchain#264]
Developing smart contracts with IBM Blockchain Platform Developer Tools 

link: https://cloud.ibm.com/docs/blockchain/howto?topic=blockchain-develop-vscode

The IBM® Blockchain Platform Developer Tools provide an environment within Visual Studio Code or Red Hat CodeReady Workspaces for developing, packaging, and testing smart contracts. You can use the tools to create your smart contract project and get started developing your business logic. You can then use the tools to test your smart contract either on your local machine by using a preconfigured instance of Hyperledger Fabric, or by connecting to an IBM Blockchain Platform network, before you deploy the smart contract to the IBM Blockchain Platform. This tutorial describes how to install and use the Developer Tools.

**Comment by jyylui** [comment]
Solved.

**Comment by altharp** [comment]
The IBM Blockchain Platform for IBM Cloud service reached end of support on July 31, 2023 and the documentation has now been removed from public access at https://cloud.ibm.com/docs/blockchain.  I am closing this issue at this point since the subject documentation is no longer available.
