### ISSUE TITLE
Image with wrong text format

### ISSUE THREAD

**Issue by ghost** [ibm-cloud-docs/blockchain#265]
I think there's something missing here.
https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-saas-pricing#ibp-saas-pricing-elements

![image](https://user-images.githubusercontent.com/79819052/128652726-18f76869-76e0-4dc7-807a-471a151c9292.png)

**Comment by altharp** [comment]
The IBM Blockchain Platform for IBM Cloud service reached end of support on July 31, 2023 and the documentation has now been removed from public access at https://cloud.ibm.com/docs/blockchain.  I am closing this issue at this point since the subject documentation is no longer available.
