### ISSUE TITLE
Page content displayed incorrect

### ISSUE THREAD

**Issue by BFuhry** [ibm-cloud-docs/blockchain#266]
On some pages of the docu, the content is not displayed/rendered correctly.

A not not exhaustive list of examples:
- https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-v2-apis#ibp-v2-apis-retrieve-service-credentials
![image](https://user-images.githubusercontent.com/89401140/137132618-8bdda2e1-92cf-4f75-81b0-62e8eb0df618.png)
- https://cloud.ibm.com/docs/blockchain?topic=blockchain-ansible
![image](https://user-images.githubusercontent.com/89401140/137132830-be3d8a98-68ba-4761-83aa-e6325066e877.png)
- https://cloud.ibm.com/docs/blockchain?topic=blockchain-ansible-build
![image](https://user-images.githubusercontent.com/89401140/137132764-fcd427e8-18bb-48c6-86a8-a21245b89234.png)

**Comment by altharp** [comment]
The IBM Blockchain Platform for IBM Cloud service reached end of support on July 31, 2023 and the documentation has now been removed from public access at https://cloud.ibm.com/docs/blockchain.  I am closing this issue at this point since the subject documentation is no longer available.
