### ISSUE TITLE
Links need to be updated

### ISSUE THREAD

**Issue by seenusuvarna** [ibm-cloud-docs/blockchain#270]
Going through the documentation located here: https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-v2-deploy-iks
Some of the links are no longer working such as the ones from the documentation:
"If you are interested in learning more about how to use IBM Blockchain Platform on Red Hat OpenShift Container Platform, Red Hat Open Kubernetes Distribution (OKD), or Kubernetes, see [Getting started with IBM Blockchain Platform 2.5.3](https://cloud.ibm.com/docs/blockchain-sw-253?topic=blockchain-sw-253-get-started-console-ocp).

If you are an experienced Hyperledger Fabric customer and are interested in learning more about how to use the IBM Blockchain peer, CA, orderer, and smart contract containers images, see [Using the IBM Blockchain images ](https://cloud.ibm.com/docs/blockchain-sw-253?topic=blockchain-sw-253-blockchain-images)."

Additionally the videos in the section need to be updated as they do not look to be correct as it does look like you can create a Kubernetes VPC based on the options when selecting a Kubernetes Service from the catalog.

Please update the docs

**Comment by altharp** [comment]
The IBM Blockchain Platform for IBM Cloud service reached end of support on July 31, 2023 and the documentation has now been removed from public access at https://cloud.ibm.com/docs/blockchain.  I am closing this issue at this point since the subject documentation is no longer available.
