### ISSUE TITLE
IBM has withdrawn the IBM Blockchain Platform SaaS edition then the related doc also should be removed

### ISSUE THREAD

**Issue by testrashmi** [ibm-cloud-docs/blockchain#272]
As per the https://cloud.ibm.com/docs/blockchain?topic=blockchain-migrating-to-hlf-support#ibp-migration-what
IBM has withdrawn the IBM Blockchain Platform SaaS edition. Blockchain is no more available in Cloud Catalog.

Can this Product Guide  be removed from Cloud Doc because customers still come on chat with queries regarding this service

**Comment by altharp** [comment]
The public documentation for IBM Blockchain Platform for IBM Cloud has been removed from https://cloud.ibm.com/docs/blockchain.  This fulfills the request in this issue, so I will close the issue at this point.
